# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a04c5854bfc4ae627f8cc872112650d9550f277acad1d5af26523d874b07ec31284ff277030edcf2ccdaa528439e2d8580f482c931cf5edabdc8506c6a898762

test:
  secret_key_base: a9509c61846bc3cdfb95111a75d5b5481a2d798eb48f2a427de22aac6db1de3a657fb511c455d14009bff89ca3bb7b5106b5c4e69c109cca0ee03e8dbb70cb86

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
